---
abstract: "syntactic sugar to complement \"has\""
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::hasn::t
name: MooseX-hasn-t
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose: 2.00
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-hasn-t
  homepage: https://metacpan.org/release/MooseX-hasn-t
  license: http://dev.perl.org/licenses/
version: 0.002
